version: "3"
tasks:
  nixos:switch:
    desc: Switches nixos configuration
    dir: "{{.ROOT_DIR}}"
    requires:
      vars:
        - NAME
    cmds:
      - sudo nixos-rebuild switch --flake .#{{.NAME}} --impure

  home-manager:switch:
    desc: Switches home-manager configuration
    dir: "{{.ROOT_DIR}}"
    cmds:
      - nix run home-manager/master -- switch --flake .#mac -b backup